name: Android NDK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - r9q-G990B2XXSJIZF1
          - pa3q-S938NKSUACZF1
          - e3q-S928USQS6DZF2
          - essi-A566EXXSCCZG6

    steps:
      - uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29
          add-to-path: true

      - name: Build ${{ matrix.target }}
        run: make TARGET=${{ matrix.target }} ANDROID_NDK_HOME=$ANDROID_NDK_HOME

      - name: Clean build artifacts
        run: make clean
        if: always()
